### PR TITLE
Macro refactor

### PR DESCRIPTION
**Pull request by stuarth**
I gave a _very_ quick (and untested -- what a PR!) refactor with another approach to the prob `defaddtoken` addresses

### CODE REVIEW

**Comment by stuarth** [comment]
couldn't resist another quick pass of cleanup. take it or leave it :)

**Comment by dkropfuntucht** [comment]
I like it.   I patched a test server with these changes, too.  Looks good.

**Comment by stuarth** [comment]
OK great. The tests are way out date unfortunately -- they'll need some
attention before they're useful

**Comment by dkropfuntucht** [comment]
Aye.  I don't think the unit test coverage on this one is anywhere near 100%.  I dropped the code in and tested our authentication module against Google and Github.  We can pull user data with Oauth2 - so it's likely good for most of APIs.

**Pull request merged**
